export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAILURE = "SIGNUP_USER_FAILURE";
export const GET_PARCEL_SUCCESS = "GET_PARCEL_SUCCESS";
export const GET_PARCEL_FAILURE = "GET_PARCEL_FAILURE";
