const actionTypes = {
  USER_AUTH_SUCCESS: "USER_AUTH_SUCCESS",
  CREATE_PARCEL_SUCCESS: "CREATE_PARCEL_SUCCESS",
  CREATE_PARCEL_FAILURE: "CREATE_PARCEL_FAILURE",
  UPDATE_PARCEL_SUCCESS: "UPDATE_PARCEL_SUCCESS",
  UPDATE_PARCEL_FAILURE: "UPDATE_PARCEL_FAILURE",
  GET_PARCELS_SUCCESS: "GET_PARCELS_SUCCESS",
  GET_PARCELS_FAILURE: "GET_PARCELS_FAILURE",
  GET_SINGLE_PARCEL_SUCCESS: "GET_SINGLE_PARCEL_SUCCESS",
  GET_SINGLE_PARCEL_FAILURE: "GET_SINGLE_PARCEL_FAILURE",
  SET_USER_ERROR: "SET_USER_ERROR",
  SET_PARCEL_ERROR: "SET_PARCEL_ERROR",
}

export default actionTypes;
