const actionTypes = {
  IS_PROCESSING: "IS_PROCESSING",
  IS_FETCHING: "IS_FETCHING",
  USER_AUTH_SUCCESS: "USER_AUTH_SUCCESS",
  USER_LOG_OUT: "USER_LOG_OUT",
  CREATE_PARCEL_SUCCESS: "CREATE_PARCEL_SUCCESS",
  UPDATE_PARCEL_SUCCESS: "UPDATE_PARCEL_SUCCESS",
  GET_PARCELS_SUCCESS: "GET_PARCELS_SUCCESS",
  GET_SINGLE_PARCEL_SUCCESS: "GET_SINGLE_PARCEL_SUCCESS",
  SET_USER_ERROR: "SET_USER_ERROR",
  SET_PARCEL_ERROR: "SET_PARCEL_ERROR",
}

export default actionTypes;
